### ISSUE TITLE
Europe Bitches

### ISSUE THREAD

**Issue by janaboruta** [janaboruta/Travel#1]
European Dates: 4/16 - 5/14
Krakow, Poland: 4/17 -  Wednesday morning 4/24 
Zlin, Czech Republic: 4/24 - 4/26
@Leehuffman leaves SF on the 25th.
@Janaboruta @Atmos: Flights- $94 Prague to Paris
Paris, France: 26th till the 29th or 30th depending on how we feel. 
@all: Flights- $121 Paris to Florence 
Florence, Italy: Hang out in Florence for a night. 
Train ride from Florence to Bucine 1 hour
Bucine: 5/1 - 5/8 
Berlin, Germany: 5/9 - 5/14

**Comment by atmos** [comment]
Sounds grood.
