### ISSUE TITLE
Praha 2014

### ISSUE THREAD

**Issue by janaboruta** [janaboruta/Travel#2]
@dylanegan

Praha Airbnb Address:
Opatovická 1661/2
Prague, Prague 110 00
Czech Republic

I plan on checking in around 14:45. The Praha central train station is about a 4 minute taxi ride to the apartment. 

Jana's European number: 420 777598857

**Comment by janaboruta** [comment]
Dinner Wednesday night 10/22
CottoCrudo, http://www.cottocrudo.cz/en
Address: Veleslavinova 1098/2a, Prague 1, 110 00 (above Charles Bridge, on our side of the river) 
Time: 21:00
3 people 

Thursday Options
U Medvidku Beer Hall Pub, Traditional Czech food
http://www.pragueexperience.com/places.asp?PlaceID=1008

The Globe
Coffee shop and english book store http://www.globebookstore.cz

Cafe Resto Patio
Amazing dinner, near our apartment
Location: Národní 22, Old Town

Best coffee and hot chocolate 
Café Kafíčko (near Prague castle) 
Address: 118 00 Praha 1-Malá Strana Czech Republic‎

@dylanegan

**Comment by dylanegan** [comment]
@janaboruta yes, :+1: :smiley:.
